version: 2
jobs:
  build:
    working_directory: ~/docker-presto-cluster
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3

      - run:
          name: Setup Docker BuildKit
          command: |
            sudo apt-get update
            sudo apt-get install make curl qemu-user -y
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create mybuilder
            docker buildx create mybuilder --driver docker-container --use
            docker buildx inspect --bootstrap

      - run:
          name: Compile for x86
          command: make build

      - run:
          name: Test
          command: make test

  deploy:
    working_directory: ~/docker-presto-cluster
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Setup Docker BuildKit
          command: |
            sudo apt-get update
            sudo apt-get install make curl qemu-user -y
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create mybuilder
            docker buildx create mybuilder --driver docker-container --use
            docker buildx inspect --bootstrap

      - run:
          name: Login
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

      - run:
          name: Deploy
          command: make push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]*/
            branches:
              ignore: /.*/